apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-secret-store
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: $HOME/Documents/Projects/dpar_lab/my-components/mysecrets.json
  - name: nestedSeparator
    value: ":"
